### PR TITLE
33 implement navbar

### PR DESCRIPTION
**Pull request by lenaray**
Screenshot 2024-05-10 at 5 09 20 PM

### CODE REVIEW

**Comment by jerrywusa** [comment]
I think hi-fi's have changed a bit, there should be the name and the selection color should be yellow:

Screenshot 2024-05-11 at 15 02 35


here is the link to hi-fi figma for reference:
https://www.figma.com/file/bneJmgZkkoiyKaSZPGilwj/Prototypes?type=design&node-id=309-341&mode=design&t=drGBdylavKxuj76d-0

**Comment by jerrywusa** [comment]
also order should be convo push contacts, I think you have it as convo contacts push

**Comment by averyli290** [comment]
Looks good to me, same comments as Jerry's. Also if you don't want to pass navigation as a prop between components, it is also possible use to the `useNavigation` hook but either way works.

**Comment by lenaray** [comment]
Screenshot 2024-05-18 at 10 47 51 AM

**Pull request merged**
